'use client';
import {useEffect,useMemo,useState} from 'react';import {useParams} from 'next/navigation';
const BASE='https://lbkdoxpanxvsrgqimzzj.supabase.co',REST=`${BASE}/rest/v1`,KEY='sb_publishable_6uNgrPI-Mj84tlHcFuICTQ_aG2zfoSU';
const data:any={
'03':{title:'Immobile',intro:'Definisci lo spazio su cui costruire il progetto.',items:['Ho individuato un immobile','Ho salvato o richiesto informazioni su un immobile','L’immobile è pronto per la verifica preliminare'],cta:'Richiedi verifica immobile',type:'property_review',link:'/immobili',linkText:'Cerca un immobile'},
'04':{title:'Normativa e requisiti',intro:'Verifichiamo requisiti regionali, comunali e strutturali prima di procedere.',items:['Regione e Comune definiti','Tipologia di struttura definita','Dati dell’immobile disponibili','Requisiti strutturali da verificare','SUAP / ASL competente da verificare'],cta:'Richiedi verifica normativa',type:'regulatory_review'},
'05':{title:'Piano economico',intro:'Costruiamo la sostenibilità economica del progetto sui dati reali.',items:['Posti previsti definiti','Budget iniziale definito','Simulazione economica aggiornata','Ricavi e costi verificati','Piano economico definitivo da validare'],cta:'Richiedi analisi economica',type:'economic_review',link:'/simulatore',linkText:'Apri il simulatore'},
'06':{title:'Autorizzazioni',intro:'Organizza le pratiche necessarie fino all’autorizzazione della struttura.',items:['Elenco autorizzazioni individuato','Pratiche SUAP verificate','Adempimenti ASL verificati','Documentazione tecnica raccolta','Autorizzazioni finali ottenute'],cta:'Avvia percorso autorizzativo',type:'authorization_support'},
'07':{title:'Personale',intro:'Definisci organico, ruoli e ricerca delle figure professionali necessarie.',items:['Figure professionali necessarie definite','Numero di persone per ruolo definito','Profili salvati o ricerca inviata','Disponibilità dei candidati verificata','Piano del personale validato'],cta:'Richiedi supporto personale',type:'staff_support',link:'/personale',linkText:'Cerca personale'},
'08':{title:'Fornitori e servizi',intro:'Costruiamo la rete di servizi necessaria al funzionamento quotidiano.',items:['Arredi e attrezzature','Sicurezza e manutenzione','Pasti e forniture','Software e servizi gestionali','Lavanderia, pulizie e assicurazioni'],cta:'Richiedi selezione fornitori',type:'supplier_support'},
'09':{title:'Apertura',intro:'Ultimo controllo prima dell’avvio operativo della struttura.',items:['Immobile verificato','Normativa e autorizzazioni completate','Piano economico validato','Personale organizzato','Fornitori e servizi attivati'],cta:'Richiedi verifica finale apertura',type:'opening_review'}};
export default function StepPage(){const params=useParams();const step=String(params.step||'');const cfg=data[step];const[token,setToken]=useState(''),[project,setProject]=useState<any>(null),[row,setRow]=useState<any>(null),[checks,setChecks]=useState<Record<string,boolean>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const headers=(json=false):Record<string,string>=>{const h:Record<string,string>={apikey:KEY};if(token)h.Authorization=`Bearer ${token}`;if(json)h['Content-Type']='application/json';return h};
 useEffect(()=>{const t=localStorage.getItem('sb-access-token')||'';if(!t){location.href='/auth';return}setToken(t);const h={apikey:KEY,Authorization:`Bearer ${t}`};fetch(`${REST}/user_projects?select=*&order=created_at.desc&limit=1`,{headers:h}).then(r=>r.json()).then(async d=>{if(!d?.[0])return;setProject(d[0]);const sr=await fetch(`${REST}/project_steps?project_id=eq.${d[0].id}&step_code=eq.${step}&select=*`,{headers:h});const sd=await sr.json();if(sd?.[0]){setRow(sd[0]);setChecks(sd[0].checklist||{})}})},[step]);
 const done=useMemo(()=>cfg?cfg.items.filter((_:string,i:number)=>checks[String(i)]).length:0,[checks,cfg]);if(!cfg)return <main className="project-page"><section className="project-empty"><h1>Fase non disponibile</h1><a href="/progetto">Torna al progetto</a></section></main>;
 async function save(next=checks){if(!project)return;setBusy(true);const status=done===cfg.items.length?'ready_for_review':done?'in_progress':'not_started';const r=await fetch(`${REST}/project_steps?project_id=eq.${project.id}&step_code=eq.${step}`,{method:'PATCH',headers:{...headers(true),Prefer:'return=representation'},body:JSON.stringify({checklist:next,status,updated_at:new Date().toISOString()})});if(r.ok){const d=await r.json();setRow(d?.[0]||row);setMessage('Progressi salvati.')}setBusy(false)}
 async function toggle(i:number){const next={...checks,[String(i)]:!checks[String(i)]};setChecks(next);setBusy(true);const count=cfg.items.filter((_:string,n:number)=>next[String(n)]).length;const status=count===cfg.items.length?'ready_for_review':count?'in_progress':'not_started';if(project)await fetch(`${REST}/project_steps?project_id=eq.${project.id}&step_code=eq.${step}`,{method:'PATCH',headers:{...headers(true),Prefer:'return=minimal'},body:JSON.stringify({checklist:next,status,updated_at:new Date().toISOString()})});setBusy(false)}
 async function request(){if(!project)return;setBusy(true);const u=await fetch(`${BASE}/auth/v1/user`,{headers:headers()}).then(r=>r.json());const r=await fetch(`${REST}/project_step_requests`,{method:'POST',headers:{...headers(true),Prefer:'return=minimal'},body:JSON.stringify({project_id:project.id,user_id:u.id,step_code:step,request_type:cfg.type,message:`Richiesta dalla fase ${step} - ${cfg.title}`,status:'new'})});if(r.ok){await fetch(`${REST}/project_steps?project_id=eq.${project.id}&step_code=eq.${step}`,{method:'PATCH',headers:{...headers(true),Prefer:'return=minimal'},body:JSON.stringify({status:'requested',requested_at:new Date().toISOString(),checklist:checks})});setMessage('Richiesta inviata ad Abitare Insieme. Ora la fase è in verifica.');setRow({...row,status:'requested'})}setBusy(false)}
 const status=row?.status||'not_started';return <main className="project-page"><header className="config-nav"><a className="brand" href="/"><span>PROGETTO</span> ABITARE INSIEME</a><a className="ghost" href="/progetto">← Il mio progetto</a></header><section className="project-welcome"><div><span className="kicker">FASE {step} DI 09</span><h1>{cfg.title}</h1><p>{cfg.intro}</p></div><div className="progress-ring"><strong>{Math.round(done/cfg.items.length*100)}%</strong><span>checklist</span></div></section><section className="project-dashboard"><div className="project-main"><div className="project-section-head"><span className="kicker">COSA DEVI FARE</span><h2>Completa i passaggi della fase</h2><p>Spunta ciò che hai già fatto. Le verifiche professionali diventano definitive solo dopo il controllo di Abitare Insieme.</p></div><div className="roadmap">{cfg.items.map((x:string,i:number)=><button key={x} onClick={()=>toggle(i)} className={`roadmap-row ${checks[String(i)]?'done':''}`} style={{width:'100%',textAlign:'left',border:'none',cursor:'pointer'}}><span className="roadmap-num">{checks[String(i)]?'✓':String(i+1).padStart(2,'0')}</span><div><strong>{x}</strong><small>{checks[String(i)]?'Completato':'Da completare'}</small></div><span className="roadmap-arrow">{checks[String(i)]?'✓':'→'}</span></button>)}</div></div><aside className="project-side"><div className="project-card"><span className="kicker">STATO DELLA FASE</span><h3>{statusLabel(status)}</h3><p>{status==='requested'?'La richiesta è stata inviata. Il team verificherà i dati e aggiornerà lo stato.':'Completa la checklist e richiedi il supporto quando sei pronto.'}</p><dl><div><dt>Completati</dt><dd>{done} / {cfg.items.length}</dd></div><div><dt>Progetto</dt><dd>{project?.municipality||'—'} · {project?.region||'—'}</dd></div></dl>{cfg.link&&<a className="ghost-button" href={cfg.link}>{cfg.linkText}</a>}<button className="button" disabled={busy||status==='requested'} onClick={request}>{status==='requested'?'Richiesta inviata':cfg.cta}</button>{message&&<p style={{marginTop:15}}><strong>{message}</strong></p>}</div><div className="project-card dark"><span className="kicker">COME FUNZIONA</span><p>1. Completi i dati disponibili.</p><p>2. Inoltri la richiesta.</p><p>3. Abitare Insieme verifica la fase.</p><p>4. Dopo la validazione la fase diventa completata ✓.</p></div></aside></section></main>}
function statusLabel(s:string){if(s==='completed')return 'Completata ✓';if(s==='requested')return 'In verifica';if(s==='ready_for_review')return 'Pronta per la verifica';if(s==='in_progress')return 'In corso';return 'Da avviare'}
