import {NextResponse} from 'next/server';
import crypto from 'crypto';
const API='https://lbkdoxpanxvsrgqimzzj.supabase.co';
const planMap:any={pro_monthly:{name:'Portale PRO',cycle:'monthly',amount:3900},pro_yearly:{name:'Portale PRO annuale',cycle:'yearly',amount:39000},assisted_monthly:{name:'Portale Assistito',cycle:'monthly',amount:9900}};
function verify(payload:string,sig:string,secret:string){const parts=Object.fromEntries(sig.split(',').map(v=>v.split('=')));if(!parts.t||!parts.v1)return false;const expected=crypto.createHmac('sha256',secret).update(`${parts.t}.${payload}`).digest('hex');try{return crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(parts.v1))}catch{return false}}
function headers(){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)throw new Error('Missing Supabase service role');return {apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:'return=minimal'}}
async function patch(table:string,filter:string,data:any){const r=await fetch(`${API}/rest/v1/${table}?${filter}`,{method:'PATCH',headers:headers(),body:JSON.stringify(data)});if(!r.ok)throw new Error(`Database update failed: ${table}`)}
async function upsertSubscription(userId:string,product:string,o:any){const plan=planMap[product];if(!plan)return;const r=await fetch(`${API}/rest/v1/user_subscriptions?on_conflict=user_id`,{method:'POST',headers:{...headers(),Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:userId,plan_code:product,plan_name:plan.name,billing_cycle:plan.cycle,amount_cents:plan.amount,currency:'EUR',status:'active',stripe_customer_id:o.customer||null,stripe_subscription_id:o.subscription||null,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error('Subscription update failed')}
export async function POST(req:Request){const payload=await req.text(),sig=req.headers.get('stripe-signature')||'',secret=process.env.STRIPE_WEBHOOK_SECRET||'';if(!secret||!verify(payload,sig,secret))return NextResponse.json({error:'Invalid signature'},{status:400});try{const event=JSON.parse(payload),o=event.data?.object||{};if(event.type==='checkout.session.completed'){const contractId=o.metadata?.contract_id||o.client_reference_id,userId=o.metadata?.user_id,product=o.metadata?.product;if(contractId)await patch('digital_contracts',`id=eq.${encodeURIComponent(contractId)}`,{status:'active',payment_status:'paid'});if(userId&&o.mode==='subscription')await upsertSubscription(userId,product,o)}if(event.type==='customer.subscription.deleted'){const sid=o.id;if(sid)await patch('user_subscriptions',`stripe_subscription_id=eq.${encodeURIComponent(sid)}`,{status:'cancelled',updated_at:new Date().toISOString()})}if(event.type==='invoice.payment_failed'){const sid=o.subscription;if(sid)await patch('user_subscriptions',`stripe_subscription_id=eq.${encodeURIComponent(sid)}`,{status:'past_due',updated_at:new Date().toISOString()})}return NextResponse.json({received:true})}catch{return NextResponse.json({error:'Webhook processing failed'},{status:500})}}
