const services = [
  ['01', 'Scopri cosa puoi aprire', 'Parti da Regione, immobile, budget e obiettivi. Il configuratore ti guida verso il percorso da approfondire.'],
  ['02', 'Verifica immobile', 'Una prima lettura di metrature, camere, accessibilita, servizi e documentazione disponibile.'],
  ['03', 'Normativa e autorizzazioni', 'Requisiti regionali, iter, enti competenti e documenti organizzati per tipologia di struttura.'],
  ['04', 'Apri con noi', 'Tecnici, consulenti, fornitori, software e supporto operativo fino all avvio della struttura.'],
];
const paths = [['Casa famiglia e piccole comunita','Per progetti residenziali contenuti e modelli a dimensione familiare.'],['Residenze e alloggi protetti','Per anziani autonomi o fragili che necessitano di un ambiente organizzato e protetto.'],['RSA e strutture sociosanitarie','Per progetti complessi rivolti alla non autosufficienza e all assistenza sociosanitaria.'],['Senior living e cohousing','Per nuovi modelli abitativi dedicati alla terza eta, anche con servizi condivisi.']];
const steps = [['1','Raccontaci il progetto','Regione, Comune, numero di ospiti, tipo di utenza e budget.'],['2','Analizziamo il punto di partenza','Se hai gia un immobile, inserisci metrature, camere, bagni e caratteristiche principali.'],['3','Ricevi un primo orientamento','Il sistema individua i percorsi compatibili da approfondire e le principali verifiche da fare.'],['4','Passa allo studio professionale','Se vuoi procedere, trasformiamo il risultato in uno studio di fattibilita operativo.']];
const featuredStaff=[{role:'OSS',place:'Torino · Piemonte',exp:'8 anni',availability:'Disponibile subito',text:'Esperienza in RSA e assistenza a persone anziane fragili. Qualifica OSS e disponibilita su turni.'},{role:'Infermiere/a',place:'Milano · Lombardia',exp:'6 anni',availability:'Disponibile in 30 giorni',text:'Esperienza in area geriatrica e residenziale. Iscrizione professionale attiva e disponibilita full time.'},{role:'Coordinatore/trice',place:'Genova · Liguria',exp:'11 anni',availability:'Valuta proposte',text:'Esperienza nella gestione di equipe, turnistica, famiglie e organizzazione di strutture residenziali.'}];
const featuredProperties=[{tag:'IN VENDITA',place:'Torino · TO',title:'Villa indipendente con giardino',price:'690.000 €',facts:'620 mq · 14 camere · 8 bagni',img:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80'},{tag:'IN AFFITTO',place:'Monza · MB',title:'Stabile su tre livelli con ascensore',price:'7.500 € / mese',facts:'980 mq · 20 camere · 12 bagni',img:'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80'},{tag:'IN VENDITA',place:'Savona · SV',title:'Ex struttura ricettiva vicino al mare',price:'1.250.000 €',facts:'1.350 mq · 28 camere · 24 bagni',img:'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80'}];
const quickNav=[['Inizia il progetto','Fai la prima valutazione','/configuratore','01'],['Il mio progetto','Continua il tuo percorso','/progetto','02'],['La mia scrivania','Documenti del tuo progetto','/progetto/scrivania','03'],['Immobili','Cerca e salva strutture','/immobili','04'],['Personale','Trova i profili che ti servono','/personale','05'],['Abbonamenti','Piani, servizi e pagamenti','/abbonamenti','06']];
const pricing=[
  {name:'START',price:'0 €',subtitle:'Per iniziare',text:'Registrazione, configuratore, prima valutazione e accesso ai contenuti pubblici del portale.',href:'/configuratore',cta:'Inizia gratis'},
  {name:'PORTALE PRO',price:'39 € / mese',subtitle:'oppure 390 € / anno',text:'La tua scrivania digitale completa con progetto, documenti, preferiti, simulatore, checklist e archivio richieste.',href:'/abbonamenti',cta:'Scopri PRO'},
  {name:'PORTALE ASSISTITO',price:'99 € / mese',subtitle:'Portale + supporto',text:'Tutto il piano PRO con supporto operativo da remoto, revisione del progetto e priorita nelle richieste.',href:'/abbonamenti',cta:'Scopri Assistito'}
];
export default function Home(){return <main><header className="nav"><a className="brand" href="#top"><span>PROGETTO</span> ABITARE INSIEME</a><nav><a href="#come-funziona">Come funziona</a><a href="#percorsi">Cosa puoi aprire</a><a href="#servizi">Servizi</a><a href="/personale">Personale</a><a href="/immobili">Immobili</a><a href="/abbonamenti">Abbonamenti</a></nav><div className="nav-actions"><a className="ghost account-link" href="/progetto">Il mio progetto</a><a className="button small" href="/configuratore">Inizia il progetto</a></div></header>
<section className="home-quick-nav"><div className="home-quick-head"><span className="kicker">VAI SUBITO A</span><strong>Tutto il portale, a portata di mano.</strong></div><div className="home-quick-grid">{quickNav.map(([title,text,href,num])=><a href={href} key={title}><span>{num}</span><div><strong>{title}</strong><small>{text}</small></div><b>→</b></a>)}</div></section>
<section className="hero" id="top"><div className="hero-copy"><div className="eyebrow">IL PORTALE PER APRIRE E GESTIRE STRUTTURE PER ANZIANI</div><h1>Il tuo progetto.<br/><em>Dall idea all apertura.</em></h1><p>Capisci cosa puoi aprire, verifica il tuo immobile, orientati tra normativa e autorizzazioni e costruisci un percorso concreto insieme a professionisti specializzati.</p><div className="actions"><a className="button" href="/configuratore">Scopri cosa puoi aprire</a><a className="ghost" href="#come-funziona">Guarda come funziona</a></div><div className="trust-row"><div><strong>3</strong><span>Regioni nella prima fase</span></div><div><strong>1</strong><span>Percorso guidato</span></div><div><strong>360</strong><span>Approccio al progetto</span></div></div></div><aside className="hero-panel"><span className="panel-kicker">PARTI DA UNA DOMANDA SEMPLICE</span><h2>Cosa vuoi aprire?</h2><div className="quick-options"><span>Casa famiglia</span><span>Comunita alloggio</span><span>Residenza protetta</span><span>RSA</span><span>Senior living</span><span>Non lo so ancora</span></div><a href="/configuratore" className="panel-link">Avvia il check preliminare →</a></aside></section>
<section className="region-strip" id="territori"><span>FASE DI LANCIO</span><strong>Piemonte</strong><strong>Lombardia</strong><strong>Liguria</strong><small>Espansione progressiva nelle altre Regioni italiane</small></section><section className="intro" id="come-funziona"><div><span className="kicker">UN SOLO PUNTO DI PARTENZA</span><h2>Aprire una struttura non deve essere un percorso al buio.</h2></div><div><p>Normative regionali, immobile, autorizzazioni, personale, investimenti e fornitori rendono il progetto complesso. Abitare Insieme organizza tutto in un percorso leggibile e progressivo.</p><p>Il portale non sostituisce i professionisti: li mette al momento giusto dentro un processo guidato.</p></div></section><section className="steps">{steps.map(([num,title,text])=><article key={num}><span>{num}</span><h3>{title}</h3><p>{text}</p></article>)}</section>
<section className="paths" id="percorsi"><div className="section-head"><span className="kicker">COSA PUOI APRIRE</span><h2>Non esiste una sola “casa per anziani”.</h2><p>La tipologia corretta dipende da Regione, ospiti, servizi, immobile e livello assistenziale.</p></div><div className="path-grid">{paths.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p><a href="/configuratore">Verifica il tuo caso →</a></article>)}</div></section><section className="services" id="servizi"><div className="section-head light"><span className="kicker">DAL CHECK ALL APERTURA</span><h2>Un ecosistema di servizi intorno al progetto.</h2></div><div className="cards">{services.map(([num,title,text])=><article key={num}><span>{num}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="paths" id="abbonamenti"><div className="section-head"><span className="kicker">PIANI E ABBONAMENTI</span><h2>Scegli quanto vuoi essere accompagnato.</h2><p>Inizia gratuitamente, usa il portale in autonomia oppure aggiungi il supporto operativo del nostro team.</p></div><div className="pricing-home-grid">{pricing.map(p=><article key={p.name}><span className="kicker">{p.subtitle}</span><h3>{p.name}</h3><h2>{p.price}</h2><p>{p.text}</p><a href={p.href}>{p.cta} →</a></article>)}</div><div className="actions" style={{marginTop:'28px'}}><a className="button" href="/abbonamenti">Vedi tutti i piani e servizi</a></div></section>
<section className="home-showcase properties-showcase"><div className="showcase-head"><div><span className="kicker">IMMOBILI IN EVIDENZA</span><h2>Spazi che possono diventare un progetto.</h2><p>Una selezione di immobili in vendita e affitto pensati per chi vuole aprire una struttura per anziani.</p></div><a className="ghost" href="/immobili">Vedi tutti gli immobili →</a></div><div className="home-property-grid">{featuredProperties.map(p=><a href="/immobili" className="home-property-card" key={p.title}><div className="home-property-image" style={{backgroundImage:`url(${p.img})`}}><span>{p.tag}</span></div><div className="home-property-content"><small>{p.place}</small><h3>{p.title}</h3><strong>{p.price}</strong><p>{p.facts}</p><span className="home-card-link">Scopri la scheda →</span></div></a>)}</div></section><section className="home-showcase staff-showcase"><div className="showcase-head light"><div><span className="kicker">PERSONALE DISPONIBILE</span><h2>Professionisti che conoscono questo settore.</h2><p>Profili anonimizzati e selezionati: il contatto viene gestito direttamente da Abitare Insieme.</p></div><a className="ghost light-link" href="/personale">Vedi tutti i profili →</a></div><div className="home-staff-grid">{featuredStaff.map((p,i)=><a href="/personale" className="home-staff-card" key={p.role+p.place}><div className="home-staff-top"><span className="staff-num">{String(i+1).padStart(2,'0')}</span><span className="staff-status">{p.availability}</span></div><span className="kicker">PROFILO RISERVATO</span><h3>{p.role}</h3><small>{p.place}</small><div className="staff-exp"><strong>{p.exp}</strong><span>di esperienza</span></div><p>{p.text}</p><span className="home-card-link light-link">Richiedi il profilo →</span></a>)}</div></section><section className="business-band"><div><span className="kicker">HAI GIA UNA STRUTTURA?</span><h2>Abitare Insieme continua anche dopo l apertura.</h2></div><p>Gestionale, digitalizzazione, AI, app per le famiglie, marketing, fornitori e nuovi servizi per strutture gia operative.</p></section><section className="cta"><span className="kicker">IL PRIMO PASSO E GRATUITO</span><h2>Hai un idea o un immobile?<br/>Partiamo da li.</h2><p>Rispondi ad alcune domande e ottieni un primo orientamento sul percorso da approfondire in Piemonte, Lombardia o Liguria.</p><a className="button gold" href="/configuratore">Avvia il configuratore</a></section><footer><div className="brand footer-brand"><span>PROGETTO</span> ABITARE INSIEME</div><p>Dall idea all apertura della tua struttura.</p><small>Le informazioni del portale hanno finalita orientativa e devono essere verificate rispetto alla normativa vigente e al caso concreto.</small></footer></main>}
