'use client';
import {useEffect,useState} from 'react';
const API='https://lbkdoxpanxvsrgqimzzj.supabase.co';const REST=`${API}/rest/v1`;const KEY='sb_publishable_6uNgrPI-Mj84tlHcFuICTQ_aG2zfoSU';
type Project={id:string;title:string;structure_type:string;region:string;municipality:string;guests:number;budget:string;property_status?:string;progress:number;current_step:string};
type Property={id:string;title:string;municipality:string;province:string;asking_price:number;listing_type:string;image_urls?:string[]};
type Candidate={id:string;public_name:string;role:string;municipality:string;province:string;experience_years:number;availability:string;photo_url?:string};
type RequestRow={id:string;kind:string;title:string;status:string;date:string};
const roadmap=[['01','Idea e configurazione'],['02','Valutazione preliminare'],['03','Immobile'],['04','Normativa e requisiti'],['05','Piano economico'],['06','Autorizzazioni'],['07','Personale'],['08','Fornitori e servizi'],['09','Apertura']];
export default function Progetto(){const[project,setProject]=useState<Project|null>(null),[loading,setLoading]=useState(true),[authenticated,setAuthenticated]=useState(false),[token,setToken]=useState(''),[properties,setProperties]=useState<Property[]>([]),[candidates,setCandidates]=useState<Candidate[]>([]),[requests,setRequests]=useState<RequestRow[]>([]),[tab,setTab]=useState('panoramica'),[notice,setNotice]=useState('');
 const h=(json=false):Record<string,string>=>{const x:Record<string,string>={apikey:KEY};if(token)x.Authorization=`Bearer ${token}`;if(json)x['Content-Type']='application/json';return x};
 useEffect(()=>{const t=localStorage.getItem('sb-access-token')||'';if(!t){setLoading(false);return}setToken(t);const headers={apikey:KEY,Authorization:`Bearer ${t}`};fetch(`${API}/auth/v1/user`,{headers}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(async()=>{setAuthenticated(true);const [pr,sp,sc,leads,propReq,staffReq]=await Promise.all([fetch(`${REST}/user_projects?select=*&order=created_at.desc&limit=1`,{headers}),fetch(`${REST}/saved_properties?select=property_id,public_properties(id,title,municipality,province,asking_price,listing_type,image_urls)&order=created_at.desc`,{headers}),fetch(`${REST}/saved_candidates?select=candidate_id,public_candidates(id,public_name,role,municipality,province,experience_years,availability,photo_url)&order=created_at.desc`,{headers}),fetch(`${REST}/leads?select=id,result_title,status,created_at&order=created_at.desc`,{headers}),fetch(`${REST}/property_requests?select=id,status,created_at,property_id&order=created_at.desc`,{headers}),fetch(`${REST}/staff_requests?select=id,role_needed,status,created_at&order=created_at.desc`,{headers})]);const pd=await pr.json(),spd=await sp.json(),scd=await sc.json(),ld=await leads.json(),prd=await propReq.json(),srd=await staffReq.json();if(Array.isArray(pd)&&pd[0])setProject(pd[0]);if(Array.isArray(spd))setProperties(spd.map((x:any)=>x.public_properties).filter(Boolean));if(Array.isArray(scd))setCandidates(scd.map((x:any)=>x.public_candidates).filter(Boolean));const rr:RequestRow[]=[];if(Array.isArray(ld))ld.forEach((x:any)=>rr.push({id:x.id,kind:'Valutazione',title:x.result_title||'Valutazione preliminare',status:x.status||'Ricevuta',date:x.created_at}));if(Array.isArray(prd))prd.forEach((x:any)=>rr.push({id:x.id,kind:'Immobile',title:'Richiesta informazioni immobile',status:x.status||'Ricevuta',date:x.created_at}));if(Array.isArray(srd))srd.forEach((x:any)=>rr.push({id:x.id,kind:'Personale',title:x.role_needed||'Ricerca personale',status:x.status||'Ricevuta',date:x.created_at}));rr.sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());setRequests(rr);setLoading(false)}).catch(()=>{localStorage.removeItem('sb-access-token');localStorage.removeItem('sb-refresh-token');setLoading(false)})},[]);
 function logout(){localStorage.removeItem('sb-access-token');localStorage.removeItem('sb-refresh-token');location.href='/auth'}
 async function removeProperty(id:string){const r=await fetch(`${REST}/saved_properties?property_id=eq.${id}`,{method:'DELETE',headers:{...h(),Prefer:'return=minimal'}});if(r.ok){setProperties(v=>v.filter(x=>x.id!==id));setNotice('Immobile rimosso dai preferiti.')}}
 async function removeCandidate(id:string){const r=await fetch(`${REST}/saved_candidates?candidate_id=eq.${id}`,{method:'DELETE',headers:{...h(),Prefer:'return=minimal'}});if(r.ok){setCandidates(v=>v.filter(x=>x.id!==id));setNotice('Profilo rimosso dai preferiti.')}}
 if(loading)return <Shell><section className="project-empty"><span className="kicker">AREA PERSONALE</span><h1>Caricamento del tuo progetto...</h1></section></Shell>;
 if(!authenticated)return <Shell><section className="project-empty"><span className="kicker">AREA PERSONALE</span><h1>Accedi al tuo progetto.</h1><p>Registrati gratuitamente per salvare valutazioni, immobili, personale e seguire il percorso fino all&apos;apertura.</p><a className="button" href="/auth">Accedi o registrati</a></section></Shell>;
 if(!project)return <Shell logout={logout}><section className="project-empty"><span className="kicker">BENVENUTO</span><h1>Crea il tuo primo progetto.</h1><p>Il configuratore costruirà la tua prima valutazione e il percorso personale.</p><a className="button" href="/configuratore">Inizia il mio progetto</a></section></Shell>;
 const p=project;const completed=Math.max(2,Math.min(9,Math.ceil((p.progress||20)/100*9)));return <Shell logout={logout}><section className="project-welcome"><div><span className="kicker">IL MIO PROGETTO</span><h1>{p.title}</h1><p>{p.structure_type||'Struttura da definire'} · {p.municipality||'Comune da definire'} · {p.region||'Regione da definire'}</p></div><div className="progress-ring"><strong>{p.progress||20}%</strong><span>completato</span></div></section>
 <nav style={{display:'flex',gap:10,flexWrap:'wrap',padding:'22px max(6vw,24px)',background:'#fff',borderBottom:'1px solid #e7e1d7'}}>{[['panoramica','Panoramica'],['richieste',`Le mie richieste (${requests.length})`],['immobili',`Immobili preferiti (${properties.length})`],['personale',`Personale preferito (${candidates.length})`],['economico','Simulazione economica'],['documenti','Documenti']].map(x=><button key={x[0]} onClick={()=>setTab(x[0])} className={tab===x[0]?'button':'ghost-button'} style={{margin:0}}>{x[1]}</button>)}</nav>{notice&&<div className="floating-success">{notice}</div>}
 {tab==='panoramica'&&<><section className="next-step"><div><span className="kicker">IL TUO PROSSIMO PASSO</span><h2>{p.current_step||'Verifica immobile e fattibilità'}</h2><p>Hai iniziato il percorso. Ora possiamo trasformare la valutazione in verifiche concrete su immobile, requisiti regionali e sostenibilità economica.</p></div><div className="next-actions"><a className="button" href="/immobili">Trova un immobile</a><a className="ghost-button" href="/configuratore">Aggiorna valutazione</a></div></section><section className="project-dashboard"><div className="project-main"><div className="project-section-head"><span className="kicker">PERCORSO DI APERTURA</span><h2>Dall&apos;idea all&apos;apertura</h2></div><div className="roadmap">{roadmap.map((s,i)=><div className={`roadmap-row ${i<completed?'done':i===completed?'active':''}`} key={s[1]}><span className="roadmap-num">{i<completed?'✓':s[0]}</span><div><strong>{s[1]}</strong><small>{i<completed?'Completato':i===completed?'Prossimo passo':'Da avviare'}</small></div><span className="roadmap-arrow">→</span></div>)}</div></div><aside className="project-side"><div className="project-card"><span className="kicker">DATI PROGETTO</span><h3>La tua idea in sintesi</h3><dl><div><dt>Tipologia</dt><dd>{p.structure_type||'Da definire'}</dd></div><div><dt>Territorio</dt><dd>{p.municipality||'—'}, {p.region||'—'}</dd></div><div><dt>Ospiti</dt><dd>{p.guests||'Da definire'}</dd></div><div><dt>Budget</dt><dd>{p.budget||'Da definire'}</dd></div><div><dt>Immobile</dt><dd>{p.property_status||'Da definire'}</dd></div></dl><a href="/configuratore">Modifica configurazione →</a></div><div className="project-card dark"><span className="kicker">IL TUO PROGETTO OGGI</span><a onClick={()=>setTab('immobili')}><strong>{properties.length} immobili salvati</strong><span>Apri la shortlist →</span></a><a onClick={()=>setTab('personale')}><strong>{candidates.length} profili salvati</strong><span>Guarda il team →</span></a><a onClick={()=>setTab('richieste')}><strong>{requests.length} richieste</strong><span>Controlla lo stato →</span></a></div></aside></section></>}
 {tab==='richieste'&&<Section title="Le mie richieste" kicker="ATTIVITÀ E CONTATTI"><p>Qui ritrovi tutte le valutazioni e le richieste inviate ad Abitare Insieme.</p><div className="roadmap">{requests.length?requests.map(r=><div className="roadmap-row" key={r.kind+r.id}><span className="roadmap-num">→</span><div><strong>{r.title}</strong><small>{r.kind} · {new Date(r.date).toLocaleDateString('it-IT')}</small></div><span>{labelStatus(r.status)}</span></div>):<Empty text="Non hai ancora inviato richieste."/>}</div></Section>}
 {tab==='immobili'&&<Section title="Immobili preferiti" kicker="LA TUA SHORTLIST"><p>Salva gli spazi interessanti e confrontali mentre il progetto prende forma.</p>{properties.length?<div className="property-grid">{properties.map(x=><article className="property-card" key={x.id}><div className="property-image" style={{backgroundImage:`url(${x.image_urls?.[0]||''})`}}><span>{x.listing_type==='rent'?'IN AFFITTO':'IN VENDITA'}</span></div><div className="property-content"><small>{x.municipality} · {x.province}</small><h3>{x.title}</h3><strong className="property-price">{new Intl.NumberFormat('it-IT').format(x.asking_price)} €{x.listing_type==='rent'?' / mese':''}</strong><a className="button" href="/immobili">Vedi e richiedi informazioni</a><button className="ghost-button" onClick={()=>removeProperty(x.id)}>♥ Rimuovi dai preferiti</button></div></article>)}</div>:<Empty text="Non hai ancora immobili preferiti." action="Scopri gli immobili" href="/immobili"/>}</Section>}
 {tab==='personale'&&<Section title="Personale preferito" kicker="IL TEAM CHE STAI COSTRUENDO"><p>Conserva qui i profili che vuoi valutare per la tua futura struttura.</p>{candidates.length?<div className="candidate-grid">{candidates.map(c=><article className="candidate-card candidate-card-photo" key={c.id}><div className="candidate-photo" style={{backgroundImage:`url(${c.photo_url||''})`}}/><div className="candidate-body"><span className="kicker">PROFILO SALVATO</span><h3>{c.public_name}</h3><strong className="candidate-role">{c.role}</strong><p>{c.municipality} · {c.province}</p><div className="candidate-stats"><div><strong>{c.experience_years}</strong><span>anni esperienza</span></div><div><strong>✓</strong><span>{c.availability}</span></div></div><a className="button" href="/personale">Richiedi questo profilo</a><button className="ghost-button" onClick={()=>removeCandidate(c.id)}>♥ Rimuovi dai preferiti</button></div></article>)}</div>:<Empty text="Non hai ancora salvato profili professionali." action="Scopri il personale" href="/personale"/>}</Section>}
 {tab==='economico'&&<Section title="Il mio simulatore economico" kicker="SOSTENIBILITÀ DEL PROGETTO"><div className="project-dashboard"><div className="project-main"><div className="project-card"><h3>La simulazione resta collegata al tuo progetto</h3><p>Posti previsti: <strong>{p.guests||'da definire'}</strong></p><p>Budget indicativo: <strong>{p.budget||'da definire'}</strong></p><p>Usa il simulatore per aggiornare investimento iniziale, ricavi, costi e sostenibilità economica.</p><a className="button" href="/simulatore">Apri / aggiorna simulazione</a></div></div><aside className="project-side"><div className="project-card dark"><span className="kicker">IMPORTANTE</span><p>La simulazione è preliminare e serve a orientare il progetto. Il piano economico definitivo viene costruito sui dati reali della struttura.</p></div></aside></div></Section>}
 {tab==='documenti'&&<Section title="Documenti del progetto" kicker="IL TUO FASCICOLO"><div className="project-card"><h3>Il fascicolo digitale è pronto.</h3><p>Qui raccoglieremo planimetrie, documenti dell&apos;immobile, preventivi, relazioni tecniche, autorizzazioni e documentazione condivisa con i professionisti.</p><div style={{padding:'22px',marginTop:20,border:'1px dashed #b9b1a4',borderRadius:16}}><strong>Nessun documento caricato</strong><p>Il caricamento documentale sarà attivato quando inizierà la verifica operativa del progetto.</p><a className="button" href="mailto:info@progettoabitareinsieme.it?subject=Documenti%20del%20mio%20progetto">Invia documenti al team</a></div></div></Section>}
 </Shell>}
function Shell({children,logout}:{children:React.ReactNode;logout?:()=>void}){return <main className="project-page"><header className="config-nav"><a className="brand" href="/"><span>PROGETTO</span> ABITARE INSIEME</a><div className="project-nav"><a href="/immobili">Immobili</a><a href="/personale">Personale</a><a href="/">Home</a>{logout&&<button className="logout-link" onClick={logout}>Esci</button>}</div></header>{children}</main>}
function Section({title,kicker,children}:{title:string;kicker:string;children:React.ReactNode}){return <section className="catalog-section"><div className="project-section-head"><span className="kicker">{kicker}</span><h2>{title}</h2></div>{children}</section>}
function Empty({text,action,href}:{text:string;action?:string;href?:string}){return <div className="project-card" style={{marginTop:24}}><h3>{text}</h3>{action&&href&&<a className="button" href={href}>{action}</a>}</div>}
function labelStatus(s:string){const v=(s||'').toLowerCase();if(v==='new'||v==='ricevuta')return 'Ricevuta';if(v==='working'||v==='in_progress')return 'In lavorazione';if(v==='contacted')return 'Ti abbiamo contattato';if(v==='closed')return 'Chiusa';return s||'Ricevuta'}
